[package]
name = "libdonow"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", features= ["serde"] }
fancy-regex = "0.13.0"
hashbrown = { version = "0.14.5", features = ["serde"] }
serde = { version = "1.0.208", features = ["serde_derive"] }
serde_json = "1.0.125"
